# Generated by Django 4.1.3 on 2022-12-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_conditionnement', '0002_remove_tconditionnement_id_and_more'),
        ('Gestion_objets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobjet',
            name='idcondit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_conditionnement.tconditionnement'),
        ),
    ]
