# Generated by Django 4.1.3 on 2022-12-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_conditionnement', '0001_initial'),
        ('Gestion_objets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDtlcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcde', models.IntegerField(blank=True, null=True)),
                ('codobj', models.IntegerField(blank=True, null=True)),
                ('qte', models.IntegerField(blank=True, null=True)),
                ('colis', models.IntegerField(blank=True, db_column='Colis', null=True)),
                ('commentaire', models.CharField(blank=True, db_column='Commentaire', max_length=100, null=True)),
            ],
            options={
                'db_table': 't_dtlcode',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='tobjet',
            name='idcondit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_conditionnement.tconditionnement'),
        ),
        migrations.AddField(
            model_name='tobjet',
            name='id_commande',
            field=models.ManyToManyField(to='Gestion_objets.tdtlcode'),
        ),
    ]
