# Generated by Django 4.1.3 on 2022-12-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_conditionnement', '0001_initial'),
        ('Gestion_objets', '0002_tdtlcode_alter_tobjet_idcondit_tobjet_id_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobjet',
            name='idcondit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_conditionnement.tconditionnement'),
        ),
    ]
