# Generated by Django 4.1.3 on 2022-12-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_objets', '0003_alter_tobjet_idcondit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tobjet',
            name='id_commande',
        ),
        migrations.AlterField(
            model_name='tobjet',
            name='idcondit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TDtlcode',
        ),
    ]
