# Generated by Django 4.1.3 on 2022-12-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_conditionnement', '0002_remove_tconditionnement_id_and_more'),
        ('Gestion_objets', '0004_remove_tobjet_id_commande_alter_tobjet_idcondit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tobjet',
            name='id',
        ),
        migrations.AlterField(
            model_name='tobjet',
            name='codobj',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tobjet',
            name='idcondit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_conditionnement.tconditionnement'),
        ),
    ]
