# Generated by Django 4.1.3 on 2022-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_objets', '0006_alter_tobjet_options_alter_tobjet_idcondit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tobjet',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='tobjet',
            name='idcondit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='tobjet',
            table='t_objet',
        ),
    ]
