# Generated by Django 4.1.3 on 2022-12-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCommunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.PositiveIntegerField(blank=True, db_column='DEP', null=True)),
                ('cp', models.CharField(blank=True, db_column='CP', max_length=5, null=True)),
                ('communes', models.CharField(blank=True, db_column='COMMUNES', max_length=50, null=True)),
            ],
            options={
                'db_table': 't_communes',
                'managed': True,
            },
        ),
    ]
