# Generated by Django 4.1.3 on 2022-12-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcommunes',
            old_name='idcom',
            new_name='idcom_id',
        ),
    ]
