# Generated by Django 4.1.3 on 2022-12-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcommunes',
            name='id_communes',
            field=models.CharField(blank=True, db_column='idCommune', max_length=5, null=True),
        ),
    ]
