# Generated by Django 4.1.3 on 2022-12-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0002_tcommunes_id_communes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcommunes',
            old_name='id_communes',
            new_name='idCommune',
        ),
    ]
