# Generated by Django 4.1.3 on 2022-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0002_rename_idcom_tcommunes_idcom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcommunes',
            name='idcom_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
