# Generated by Django 4.1.3 on 2022-12-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0003_rename_id_communes_tcommunes_idcommune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcommunes',
            old_name='idCommune',
            new_name='idcommune',
        ),
    ]
