# Generated by Django 4.1.3 on 2022-12-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0004_rename_idcommune_tcommunes_idcommune'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcommunes',
            options={'managed': False},
        ),
    ]
