# Generated by Django 4.1.3 on 2022-12-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0005_alter_tcommunes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcommunes',
            options={'managed': True},
        ),
    ]
