# Generated by Django 4.1.3 on 2022-12-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0006_alter_tcommunes_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcommunes',
            old_name='idcommune',
            new_name='idCommune',
        ),
    ]
