# Generated by Django 4.1.3 on 2022-12-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0007_rename_idcommune_tcommunes_idcommune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcommunes',
            name='idCommune',
        ),
    ]
