# Generated by Django 4.1.3 on 2022-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0008_remove_tcommunes_idcommune'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcommunes',
            name='idcom',
            field=models.CharField(blank=True, db_column='idcom', max_length=5, null=True),
        ),
    ]
