# Generated by Django 4.1.3 on 2022-12-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0009_tcommunes_idcom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcommunes',
            name='ville',
            field=models.CharField(blank=True, db_column='ville', max_length=50, null=True),
        ),
    ]
