# Generated by Django 4.1.3 on 2022-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0010_tcommunes_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcommunes',
            name='id',
        ),
        migrations.AlterField(
            model_name='tcommunes',
            name='idcom',
            field=models.CharField(blank=True, db_column='idcom', max_length=5, primary_key=True, serialize=False),
        ),
    ]
