# Generated by Django 4.1.3 on 2022-12-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0011_remove_tcommunes_id_alter_tcommunes_idcom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcommunes',
            name='ville',
        ),
    ]
