# Generated by Django 4.1.3 on 2022-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0013_alter_tcommunes_idcom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcommunes',
            name='idcom',
            field=models.AutoField(db_column='idcom', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
