# Generated by Django 4.1.3 on 2022-11-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_alter_tutilisateur_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutilisateur',
            options={'managed': False},
        ),
    ]
