# Generated by Django 4.1.3 on 2022-12-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_alter_tutilisateur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutilisateur',
            options={'managed': True},
        ),
    ]
