# Generated by Django 4.1.3 on 2022-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0004_alter_tutilisateur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutilisateur',
            name='nom_utilisateur',
            field=models.CharField(max_length=128),
        ),
    ]
