# Generated by Django 4.1.3 on 2022-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TDtlcode',
            fields=[
                ('commande_id', models.AutoField(primary_key=True, serialize=False)),
                ('codcde', models.IntegerField(blank=True, null=True)),
                ('codobj', models.IntegerField(blank=True, null=True)),
                ('qte', models.IntegerField(blank=True, null=True)),
                ('colis', models.IntegerField(blank=True, db_column='Colis', null=True)),
                ('commentaire', models.CharField(blank=True, db_column='Commentaire', max_length=100, null=True)),
            ],
            options={
                'db_table': 't_dtlcode',
                'managed': False,
            },
        ),
    ]
