# Generated by Django 4.1.3 on 2022-12-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ligne_commande', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tdtlcode',
            options={'managed': True},
        ),
    ]
