# Generated by Django 4.1.3 on 2022-12-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ligne_commande', '0002_alter_tdtlcode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdtlcode',
            name='codcde',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tdtlcode',
            name='commande_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
