# Generated by Django 4.1.3 on 2022-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ligne_commande', '0003_alter_tdtlcode_codcde_alter_tdtlcode_commande_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdtlcode',
            name='commande_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
