# Generated by Django 4.1.3 on 2022-12-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TConditionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcondit', models.IntegerField()),
                ('libcondit', models.CharField(blank=True, max_length=50, null=True)),
                ('poidscondit', models.IntegerField(blank=True, null=True)),
                ('prixcond', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('ordreimp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_conditionnement',
                'managed': True,
            },
        ),
    ]
