# Generated by Django 4.1.3 on 2022-12-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_conditionnement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tconditionnement',
            name='id',
        ),
        migrations.AlterField(
            model_name='tconditionnement',
            name='idcondit',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
