# Generated by Django 4.1.3 on 2022-12-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_conditionnement', '0002_remove_tconditionnement_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tconditionnement',
            old_name='idcondit',
            new_name='idcondit_id',
        ),
    ]
