# Generated by Django 4.1.3 on 2022-12-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_conditionnement', '0003_rename_idcondit_tconditionnement_idcondit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tconditionnement',
            name='idcondit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
