# Generated by Django 4.1.3 on 2022-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TClient',
            fields=[
                ('codcli_id', models.AutoField(primary_key=True, serialize=False)),
                ('genrecli', models.CharField(blank=True, max_length=8, null=True)),
                ('nomcli', models.CharField(max_length=40)),
                ('prenomcli', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse1cli', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse2cli', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse3cli', models.CharField(blank=True, max_length=255, null=True)),
                ('cpcli', models.CharField(blank=True, max_length=5, null=True)),
                ('villecli', models.CharField(blank=True, max_length=50, null=True)),
                ('telcli', models.CharField(blank=True, max_length=10, null=True)),
                ('emailcli', models.TextField(blank=True, null=True)),
                ('portcli', models.CharField(blank=True, max_length=10, null=True)),
                ('newsletter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_client',
                'managed': False,
            },
        ),
    ]
