# Generated by Django 4.1.3 on 2022-12-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tclient',
            options={'managed': True},
        ),
    ]
