# Generated by Django 4.1.3 on 2022-12-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_communes', '0003_alter_tcommunes_idcom_id'),
        ('Gestion_client', '0002_alter_tclient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tclient',
            name='idcom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_communes.tcommunes'),
        ),
    ]
