# Generated by Django 4.1.3 on 2022-12-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TPoids',
            fields=[
                ('valmin', models.FloatField(primary_key=True, serialize=False)),
                ('valtimbre', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_poids',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TPoidsv',
            fields=[
                ('valmin', models.FloatField(primary_key=True, serialize=False)),
                ('valtimbre', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_poidsv',
                'managed': True,
            },
        ),
    ]
