# Generated by Django 4.1.3 on 2022-12-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ligne_commande', '0002_alter_tdtlcode_options'),
        ('Gestion_client', '0003_tclient_idcom'),
        ('Gestion_commandes', '0002_alter_tentcde_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentcde',
            name='codcli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_client.tclient'),
        ),
        migrations.AddField(
            model_name='tentcde',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_ligne_commande.tdtlcode'),
        ),
    ]
