# Generated by Django 4.1.3 on 2022-12-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_commandes', '0003_tentcde_codcli_tentcde_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tentcde',
            old_name='commande',
            new_name='commande_id',
        ),
        migrations.AlterField(
            model_name='tentcde',
            name='codcde',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
