# Generated by Django 4.1.3 on 2022-12-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ligne_commande', '0003_alter_tdtlcode_codcde_alter_tdtlcode_commande_id'),
        ('Gestion_commandes', '0004_rename_commande_tentcde_commande_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentcde',
            name='commande_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_ligne_commande.tdtlcode'),
        ),
    ]
